# Generated by Django 5.0 on 2024-04-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploader',
            new_name='upload_model',
        ),
    ]
